#!/usr/bin/env python3
"""Extract local customizations of agent.yaml into agent.local.yaml.

Сравнивает `agents/<name>/agent.yaml` в working tree с upstream-версией
(`git show origin/<branch>:agents/<name>/agent.yaml`). Все поля, у которых
значение ОТЛИЧАЕТСЯ от upstream, записываются в `agent.local.yaml` рядом
с исходником. После этого сам `agent.yaml` можно откатывать к upstream
(`git checkout origin/<branch> -- ...`) — правки уже сохранены в overlay.

Usage:
    python3 scripts/extract_local_config.py <path-to-agent.yaml> [--branch main]

Поведение:
  - Если local.yaml уже существует — выходит с кодом 0 (skip), не перезатирая.
  - Если upstream-версия недоступна (файл новый) — skip с кодом 0.
  - Если local.yaml пустой (нет отличий) — skip с кодом 0.
  - Ошибки ввода/git → stderr + exit 1.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import yaml


def _run_git(args: list[str], cwd: Path) -> tuple[int, str, str]:
    """Запустить git, вернуть (returncode, stdout, stderr)."""
    proc = subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )
    return proc.returncode, proc.stdout, proc.stderr


def _repo_root(start: Path) -> Path:
    code, out, _ = _run_git(
        ["rev-parse", "--show-toplevel"], start if start.is_dir() else start.parent
    )
    if code != 0:
        raise RuntimeError(f"{start}: не git-репозиторий")
    return Path(out.strip())


def _rel_in_repo(path: Path, repo_root: Path) -> str:
    """Путь относительно корня репо, нормализованный для git show (`/`)."""
    return path.resolve().relative_to(repo_root).as_posix()


def _load_upstream(
    path_in_repo: str, branch: str, repo_root: Path
) -> dict | None:
    """Получить upstream YAML как dict, или None если файла нет в upstream."""
    code, out, err = _run_git(
        ["show", f"origin/{branch}:{path_in_repo}"], repo_root
    )
    if code != 0:
        if "does not exist" in err or "exists on disk" in err:
            return None
        raise RuntimeError(f"git show failed: {err.strip()}")
    try:
        data = yaml.safe_load(out) or {}
    except yaml.YAMLError as e:
        raise RuntimeError(f"upstream YAML парсится с ошибкой: {e}")
    if not isinstance(data, dict):
        raise RuntimeError("upstream YAML — не mapping, миграция невозможна")
    return data


def _load_local_raw(path: Path) -> dict:
    """Прочитать локальный YAML. БЕЗ expandvars — нам нужны сырые литералы
    (`${TOKEN}` должно попасть в overlay как есть, не раскрываться).
    """
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise RuntimeError(f"{path}: YAML — не mapping")
    return data


def diff_overlay(base: dict, local: dict) -> dict:
    """Минимальный overlay: только поля, значения которых РЕАЛЬНО отличаются.

    Логика обратная `_deep_merge` из src/agent.py:
      - если ключа нет в base → кладём полное значение local
      - если оба dict → рекурсивный diff; если поддиф пустой, ключ пропускаем
      - иначе (скаляр/список/None) → если значения не равны, кладём local
    """
    out: dict = {}
    for key, local_val in local.items():
        if key not in base:
            out[key] = local_val
            continue
        base_val = base[key]
        if isinstance(base_val, dict) and isinstance(local_val, dict):
            sub = diff_overlay(base_val, local_val)
            if sub:
                out[key] = sub
        elif base_val != local_val:
            out[key] = local_val
    return out


def extract(agent_yaml: Path, branch: str = "main") -> tuple[str, Path | None]:
    """Основная логика, возвращает (status, local_path_if_written).

    status ∈ {"written", "skip-no-diff", "skip-exists", "skip-no-upstream"}
    """
    agent_yaml = agent_yaml.resolve()
    if not agent_yaml.is_file():
        raise RuntimeError(f"{agent_yaml}: файл не найден")

    local_path = agent_yaml.with_name("agent.local.yaml")
    if local_path.exists():
        return "skip-exists", None

    repo_root = _repo_root(agent_yaml.parent)
    rel = _rel_in_repo(agent_yaml, repo_root)

    upstream = _load_upstream(rel, branch, repo_root)
    if upstream is None:
        return "skip-no-upstream", None

    local = _load_local_raw(agent_yaml)
    overlay = diff_overlay(upstream, local)
    if not overlay:
        return "skip-no-diff", None

    header = (
        "# Local overrides for agent.yaml — keeps user customizations across git pulls.\n"
        "# Generated by scripts/extract_local_config.py.\n"
        "# Feel free to edit by hand: fields here are deep-merged over agent.yaml.\n"
    )
    local_path.write_text(
        header + yaml.dump(overlay, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
    return "written", local_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("agent_yaml", type=Path, help="path to agents/<name>/agent.yaml")
    parser.add_argument("--branch", default="main", help="upstream branch (default: main)")
    args = parser.parse_args(argv)

    try:
        status, out_path = extract(args.agent_yaml, branch=args.branch)
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if status == "written":
        print(f"wrote {out_path}")
    elif status == "skip-exists":
        print(f"skip {args.agent_yaml}: agent.local.yaml уже существует")
    elif status == "skip-no-upstream":
        print(f"skip {args.agent_yaml}: нет в upstream (новый файл)")
    elif status == "skip-no-diff":
        print(f"skip {args.agent_yaml}: нет отличий от upstream")
    return 0


if __name__ == "__main__":
    sys.exit(main())
